# Generated by Django 5.0.3 on 2026-04-12 20:26

from django.db import migrations


def clear_removed_gender_values(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(gender__in=("O", "N")).update(gender=None)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(clear_removed_gender_values, noop_reverse),
    ]
