"""
Configuration for Tunisia product search agent.
Store definitions: name, search URL template, and CSS selectors for product cards, title, price, link.
"""

# Each store belongs to one or more verticals used for category-scoped search (see categories.py).

STORES = [
    {
        "id": "mytek",
        "name": "Mytek",
        "categories": ["electronics"],
        "base_url": "https://www.mytek.tn",
        "search_url": "https://www.mytek.tn/recherche?controller=search&s={query}",
        "selectors": {
            "product_card": "article.product-miniature, .product-item, .item-product",
            "title": "h2.product-title a, .product-title a, a.product-name",
            "price": ".product-price-and-shipping .price, .current-price, .price",
            "link": "h2.product-title a, .product-title a, a.product-name",
            "image": ".product-cover img, .product-thumbnail img, .product-miniature img, img",
        },
    },
    {
        "id": "tunisianet",
        "name": "Tunisianet",
        "categories": ["electronics"],
        "base_url": "https://www.tunisianet.com.tn",
        "search_url": "https://www.tunisianet.com.tn/recherche?controller=search&s={query}",
        "selectors": {
            "product_card": "article.product-miniature, .product-miniature, .item-product",
            "title": "h2.product-title a, .product-title a, .product-name a",
            "price": ".product-price-and-shipping .price, .current-price-value, .price",
            "link": "h2.product-title a, .product-title a, a.product-name",
            "image": ".product-cover img, .product-thumbnail img, .product-miniature img, img",
        },
    },
    {
        "id": "wiki",
        "name": "Wiki Tunisie",
        "categories": ["electronics"],
        "base_url": "https://www.wiki.tn",
        "search_url": "https://www.wiki.tn/recherche?controller=search&s={query}",
        "selectors": {
            "product_card": "article.product-miniature, .product-item",
            "title": "h2.product-title a, .product-title a",
            "price": ".product-price-and-shipping .price, .current-price, .price",
            "link": "h2.product-title a, .product-title a",
            "image": ".product-cover img, .product-thumbnail img, img",
        },
    },
    # Grocery / food — Géant Drive (category page for yogurt/yaourt; site has no global search)
    {
        "id": "geantdrive",
        "name": "Géant Drive",
        "categories": ["food"],
        "base_url": "https://www.geantdrive.tn",
        "search_url": "https://www.geantdrive.tn/recherche?controller=search&s={query}",
        # Search pages often have no SSR product cards; use real category URLs when possible.
        "category_url": "https://www.geantdrive.tn/tunis-city/142-yaourts-et-cremes-dessert",
        "category_queries": ["yaourt", "yogurt"],
        "category_routes": {
            "milk": "https://www.geantdrive.tn/tunis-city/152-laits",
            "lait": "https://www.geantdrive.tn/tunis-city/152-laits",
            "dairy": "https://www.geantdrive.tn/tunis-city/152-laits",
            "yaourt": "https://www.geantdrive.tn/tunis-city/142-yaourts-et-cremes-dessert",
            "yogurt": "https://www.geantdrive.tn/tunis-city/142-yaourts-et-cremes-dessert",
        },
        "selectors": {
            "product_card": "article.product-miniature, .product-miniature, .product-item",
            "title": "h2.product-title a, .product-title a, .product-name a",
            "price": ".product-price-and-shipping .price, .current-price, .price",
            "link": "h2.product-title a, .product-title a, a.product-name",
            "image": ".product-cover img, .product-thumbnail img, img",
        },
    },
    # Parapharmacie / cosmetics / health
    {
        "id": "cosmedic",
        "name": "Cosmedic",
        "categories": ["cosmetics", "pharmacy"],
        "base_url": "https://www.cosmedic.tn",
        "search_url": "https://www.cosmedic.tn/recherche?controller=search&s={query}",
        "selectors": {
            "product_card": "article.product-miniature, .product-miniature, .product-item",
            "title": "h2.product-title a, .product-title a, .product-name a",
            "price": ".product-price-and-shipping .price, .current-price, .price",
            "link": "h2.product-title a, .product-title a, a.product-name",
            "image": ".product-cover img, .product-thumbnail img, img",
        },
    },
    {
        "id": "coquette",
        "name": "Coquette",
        "categories": ["cosmetics", "pharmacy"],
        "base_url": "https://www.coquette.tn",
        "search_url": "https://www.coquette.tn/recherche?controller=search&s={query}",
        "selectors": {
            "product_card": "article.product-miniature, .product-miniature, .product-item",
            "title": "h2.product-title a, .product-title a, .product-name a",
            "price": ".product-price-and-shipping .price, .current-price, .price",
            "link": "h2.product-title a, .product-title a, a.product-name",
            "image": ".product-cover img, .product-thumbnail img, img",
        },
    },
    {
        "id": "parapharmacie_tn",
        "name": "Parapharmacie.tn",
        "categories": ["cosmetics", "pharmacy"],
        "base_url": "https://parapharmacie.tn",
        "search_url": "https://parapharmacie.tn/?s={query}&post_type=product",
        "selectors": {
            "product_card": "ul.products li.product",
            "title": "h2.woocommerce-loop-product__title, .woocommerce-loop-product__title",
            "price": ".price",
            "link": "a.woocommerce-LoopProduct-link, a.woocommerce-loop-product__link",
            "image": "a.woocommerce-LoopProduct-link img, img.attachment-woocommerce_thumbnail, img",
        },
    },
    {
        "id": "pharma_shop",
        "name": "Pharma-shop.tn",
        "categories": ["cosmetics", "pharmacy"],
        "base_url": "https://pharma-shop.tn",
        "search_url": "https://pharma-shop.tn/recherche?controller=search&s={query}",
        "selectors": {
            "product_card": "article.product-miniature, .product-miniature, .product-item",
            "title": "h2.product-title a, .product-title a, .product-name a",
            "price": ".product-price-and-shipping .price, .current-price, .price",
            "link": "h2.product-title a, .product-title a, a.product-name",
            "image": ".product-cover img, .product-thumbnail img, img",
        },
    },
    {
        "id": "parashop",
        "name": "Parashop.tn",
        "categories": ["cosmetics", "pharmacy"],
        "base_url": "https://www.parashop.tn",
        "search_url": "https://www.parashop.tn/index.php?route=product/search&search={query}",
        "selectors": {
            "product_card": ".product-thumb",
            "title": "div.name a, .caption .name a",
            "price": ".price",
            "link": "a.product-img, div.name a",
            "image": "a.product-img img, .image img",
        },
    },
]

# Optional French/English query variants so French-language Tunisian sites return results
# Use specific terms (e.g. "contour levres" for lip liner) to avoid broad matches
# If the query contains any keyword for a category, "auto" mode only searches stores in that vertical.
# Short tokens use word boundaries inside categories.infer logic.
CATEGORY_QUERY_KEYWORDS: dict[str, list[str]] = {
    "food": [
        "yogurt",
        "yaourt",
        "yoghurt",
        "lait",
        "milk",
        "fromage",
        "cheese",
        "pain",
        "bread",
        "riz",
        "rice",
        "pâte",
        "pates",
        "pâtes",
        "pasta",
        "beurre",
        "butter",
        "oeuf",
        "œuf",
        "egg",
        "huile",
        "olive",
        "sucre",
        "sugar",
        "café",
        "coffee",
        "thé",
        "tea",
        "jus",
        "juice",
        "eau minérale",
        "semoule",
        "couscous",
        "farine",
        "flour",
        "tomate",
        "tomato",
        "légume",
        "legume",
        "fruit",
        "viande",
        "meat",
        "poulet",
        "chicken",
        "poisson",
        "fish",
        "épicerie",
        "epicerie",
        "grocery",
        "supermarché",
        "supermarche",
        "nutella",
        "chocolat",
        "chocolate",
        "biscuit",
        "céréale",
        "cereale",
        "yaourts",
    ],
    "electronics": [
        "iphone",
        "ipad",
        "macbook",
        "samsung galaxy",
        "galaxy s",
        "galaxy a",
        "laptop",
        "ordinateur",
        "pc portable",
        "téléviseur",
        "televiseur",
        "smart tv",
        "écran",
        "ecran gaming",
        "gaming",
        "souris",
        "clavier",
        "console",
        "playstation",
        "xbox",
        "nintendo",
        "téléphone",
        "telephone",
        "smartphone",
        "casque",
        "enceinte bluetooth",
        "tablette",
        "chargeur",
        "câble usb",
        "cable usb",
        "routeur",
        "modem",
        "disque dur",
        "ssd",
        "mémoire ram",
        "memoire ram",
        "processeur",
        "carte graphique",
        "gpu",
        "four électrique",
        "four electrique",
        "réfrigérateur",
        "refrigerateur",
        "frigo",
        "lave linge",
        "lave-vaisselle",
        "micro-onde",
        "micro onde",
        "aspirateur",
        "mytek",
        "tunisianet",
    ],
    "cosmetics": [
        "facewash",
        "face wash",
        "cleanser",
        "nettoyant",
        "crème",
        "creme",
        "shampoo",
        "shampoing",
        "après-shampoing",
        "apres shampoing",
        "mascara",
        "rouge à lèvres",
        "rouge a levres",
        "parfum",
        "eau de toilette",
        "gel douche",
        "savon",
        "soap",
        "cosmétique",
        "cosmetique",
        "makeup",
        "maquillage",
        "sunscreen",
        "écran solaire",
        "ecran solaire",
        "hydratant",
        "sérum",
        "serum",
        "lotion",
        "déodorant",
        "deodorant",
        "rasoir",
        "épilation",
        "epilation",
        "vernis",
        "ongle",
        "fond de teint",
        "anticernes",
        "blush",
        "highlighter",
        "contour",
        "levres",
        "lèvres",
        "lipstick",
        "eyeliner",
    ],
    "pharmacy": [
        "vitamine",
        "vitamin",
        "complément alimentaire",
        "complement alimentaire",
        "aspirine",
        "paracétamol",
        "paracetamol",
        "ibuprofène",
        "ibuprofene",
        "médicament",
        "medicament",
        "sirop",
        "antibiotique",
        "pansement",
        "sparadrap",
        "bandage",
        "antiseptique",
        "homéopathie",
        "homeopathie",
        "probiotic",
        "probiotique",
        "omega",
        "oméga",
        "collagène",
        "collagene",
        "pharmacie",
        "parapharmacie",
    ],
}

QUERY_VARIANTS = {
    "yogurt": ["yaourt"],
    "yaourt": ["yogurt"],
    "lip liner": ["contour levres", "crayon contour levres"],
    "lip liners": ["contour levres", "crayon contour levres"],
    "lip-liner": ["contour levres", "crayon contour levres"],
}

# HTTP headers to mimic a real browser (reduce block risk)
DEFAULT_HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "fr-FR,fr;q=0.9,en;q=0.8",
    "Accept-Encoding": "gzip, deflate, br",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1",
}

REQUEST_TIMEOUT = 15
MAX_RESULTS_PER_STORE = 10
