# Generated by Django 5.0.3 on 2026-04-12 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_key', models.CharField(db_index=True, max_length=96)),
                ('value', models.FloatField(default=0.0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_affinities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-value', '-updated_at'),
                'unique_together': {('user', 'brand_key')},
            },
        ),
    ]
